### ISSUE TITLE
【严重】回调逻辑建议

### ISSUE THREAD

**Issue by lk125454242** [ali-sdk/node-dingtalk#10]
创建用户失败的时候 竟然 直接 throw err 了 不走回到回调函数中，让我的下一步操作无法继续。
lib/api/client.js line : 50

**Comment by atian25** [comment]
?? 给出详细一点的信息? 

另外, `lib/api/client.js line : 50` 是空行, 直接给 url

创建失败是 throw 的, 自己 catch 下?
