### ISSUE TITLE
Could typings be added to this repo?

### ISSUE THREAD

**Issue by taoqf** [ali-sdk/node-dingtalk#11]
Typings would be very gentle for user who use TypeScript like me. Thank you all.

**Comment by atian25** [comment]
PR is welcome

**Comment by taoqf** [comment]
I just finished [dd](https://github.com/taoqf/ali-dd/blob/master/index.d.ts)

**Comment by atian25** [comment]
@taoqf 👍  so any QuickStart doc for newers ?

**Comment by taoqf** [comment]
Aha, I have not used this yet. 
I have added some [doc](https://github.com/taoqf/ali-dd) for newers in TypeScript.

**Comment by taoqf** [comment]
And I forked this repo, trying add types.

**Comment by atian25** [comment]
waiting for PR~

**Comment by taoqf** [comment]
Will the `yield` function be changed into `async`?

**Comment by atian25** [comment]
only utils 8.x to be LTS, maybe October

**Comment by taoqf** [comment]
[It](https://github.com/ali-sdk/node-dingtalk/pull/13) really took me a lot of time. But I think this would help other people.

**Comment by SilverLeaves** [comment]
maybe it should rewrite with typescript。

**Comment by SilverLeaves** [comment]
maybe it should be rewrite with typescript。

附带一张以前对小程序提的工单，可以基本推论得出：**靠钉钉官方提供type是不太可能的**
![图片](https://user-images.githubusercontent.com/31165554/58067247-3c2c0a80-7bbf-11e9-93f4-039ce8ff212b.png)

**Comment by shiny** [comment]
朋友们，现在来到了公元2021年

**Comment by shiny** [comment]
现在已经推荐使用 `@aliyun/dingtalk` 了，有 ts 支持，这个 issue 可以关闭了

**Comment by shiny** [comment]
现在已经推荐使用 `@aliyun/dingtalk` 了，有 ts 支持，这个 issue 可以关闭了
