### ISSUE TITLE
自己周末封装一个dd sdk后，才发现这个sdk

### ISSUE THREAD

**Issue by johnnychen** [ali-sdk/node-dingtalk#17]
参见：

https://github.com/cathayjs/egg-dd-sdk

其中，dd-aes加解密是自己摸索，折腾了很久才搞定的：

https://github.com/cathayjs/nodejs-dd-aes

看看有没有可以拿来用的，另外，请教下@atian25你封装这个sdk的动机在哪里呢？你应该不是钉钉这边的同学把？没看到钉钉官方文档中有nodejs的sdk介绍

**Comment by atian25** [comment]
动机就是我之前有业务需要... 就封了个呗.

已经跟钉钉那边的同学打过招呼了，后面他们有空了会接手过去。

**Comment by johnnychen** [comment]
soga, 一样的，我们主要做员工集成、微应用开发、流程审批、单点登陆。

你做的话肯尼顶不是阿里钉钉与员工集成，是微应用及钉钉消息？

**Comment by atian25** [comment]
不是 isv 的，就简单实现了几个服务端的接口。

**Comment by johnnychen** [comment]
好的，回头我想想咋整合下这些个sdk:)
