### ISSUE TITLE
钉钉备忘

### ISSUE THREAD

**Issue by atian25** [ali-sdk/node-dingtalk#2]
- 命名不统一, 有全小写和驼峰
- `user/create` 已经存在用户时, 未返回对应的 userid
- `user/update` 未返回对应的 userid, 而 `department/update` 返回了对应的 id
- `getUseridByUnionid` 对应的是 `user.openId`
- js api 签名: url 要特殊处理.... 给的 php 示例是有 bug 的
  
  > https://open-doc.dingtalk.com/doc2/detail.htm?spm=a219a.7386797.0.0.WXYE3B&treeId=171&articleId=104934&docType=1
  > 
  > 注意：若页面url为http://abc.com?url=http%3A%2F%2Fabc.com%2somewhere，则用于生成签名的url应对query部分做一次urldecode，正确结果应为http://abc.com?url=http://abc.com/somewhere

**Comment by atian25** [comment]
`media/post` 文档非常不清晰

**Comment by atian25** [comment]
自动化测试比较麻烦, 需要自己手机注册的企业, 而且反复删除 user 还是会达到 user 上线 (已删除也算在内), 后面看看能否找钉钉同学要下测试账号

**Comment by SilverLeaves** [comment]
这个ISSUE两年了？

**Comment by atian25** [comment]
[摊手] 毕竟这个是非官方的类库，有需要的同学，向钉钉开放平台反馈吧
