### ISSUE TITLE
`user.listAll()`触发并发限制

### ISSUE THREAD

**Issue by SilverLeaves** [ali-sdk/node-dingtalk#32]
* **Node Version**: 10.15.1
* **Platform**: win10

## 调用 `user.listAll()`触发。
``` bash
2019-02-13 20:40:05,005 ERROR 7868 [-/127.0.0.1/-/687ms GET /syncUser] 同步失败: 
"https://oapi.dingtalk.com/user/list got error: 
{\"errmsg\":\"您的服务器调用钉钉开放平台当前接口的所有请求都被暂时禁用了,
 apiPath(/user/list), 从 2019-02-13 20:40:04 到 2019-02-13 20:40:04 
请求总次数超过了 300 次, 处罚将在 2019-02-13 20:40:05 结束.\",\"errcode\":90002}"
```

**Comment by SilverLeaves** [comment]
https://github.com/sindresorhus/p-all/issues/3

**Comment by atian25** [comment]
https://github.com/ali-sdk/node-dingtalk/blob/master/lib/api/user.js#L72

pass `opts.concurrency`

**Comment by atian25** [comment]
但错误提示是，`从 2019-02-13 20:40:04 到 2019-02-13 20:40:04 请求总次数超过了 300 次, 处罚将在 2019-02-13 20:40:05 结束`

这就没办法了，不允许你请求那么多次

**Comment by SilverLeaves** [comment]
@atian25 网络速度太快了，我传的1，仍然会有几率触发。

**Comment by atian25** [comment]
一个部门那么多人么？

**Comment by SilverLeaves** [comment]
@atian25 整个公司的

**Comment by atian25** [comment]
这个就跟 SDK 无关了，是钉钉提供的 API，一般这种拿到整个部门的用户信息，是非常敏感的接口，现在能给你遍历就已经很不错了。

**Comment by atian25** [comment]
而且你要检查下你的逻辑，是不是跟用户请求无关的（而不是每一个请求，就来查询一次，要缓存），一般都是搞个定时任务同步。

**Comment by SilverLeaves** [comment]
开发钉钉心好累！
