### ISSUE TITLE
可以更新一下版本吗，这两年没更新了，钉钉的服务端接口都变了

### ISSUE THREAD

**Issue by Akimotorakiyu** [ali-sdk/node-dingtalk#33]
可以更新一下版本吗，这一年没更新了，钉钉的服务端接口都变了

* **Node Version**: 10.15.3
* **Platform**: eggjs, midwayjs

给钉钉提过的工单
![图片](https://user-images.githubusercontent.com/31165554/57289877-ce77dd00-70ee-11e9-8e2b-883ce6fc0e71.png)

**Comment by atian25** [comment]
抱歉，我这边不是钉钉的维护人员，这个 SDK 也不是钉钉官方的 SDK，只是一个社区模块。

欢迎提供 Pull Request 支持下。同时我这边也会试着找下钉钉那边的研发反馈下。

**Comment by SilverLeaves** [comment]
@atian25 我没提PR的水平呀，我要是会写测试，我去年就提了。心有余而力不足鸭！

**Comment by atian25** [comment]
我反馈给钉钉那边的同学了，看他们有没有计划

**Comment by SilverLeaves** [comment]
![图片](https://user-images.githubusercontent.com/31165554/57289240-99b75600-70ed-11e9-8d18-523f72795a25.png)

**Comment by SilverLeaves** [comment]
![图片](https://user-images.githubusercontent.com/31165554/58066892-dd19c600-7bbd-11e9-8160-cd89cbaa4ed5.png)

**Comment by JianmingXia** [comment]
最近由于工作原因，封装了一些钉钉官方的API，觉得官方版本不太适用的可以参考：https://github.com/JianmingXia/node-dingtalk-latest。如果有问题，也欢迎提 ISSUE

**Comment by SilverLeaves** [comment]
截止目前，仍无node-sdk
![图片](https://user-images.githubusercontent.com/31165554/62504728-67bca980-b82c-11e9-9be6-0aa11447a8cd.png)

**Comment by JianmingXia** [comment]
@SilverLeaves 官方是不指望了，只能自己动手了。。。

**Comment by allenm** [comment]
@SilverLeaves @JianmingXia 现在主要是哪些接口用不了？能整理下你这边的需求吗？我来推进下先解决你们亟需的一些接口。

**Comment by JianmingXia** [comment]
@allenm 调用方式就不太一样，比如已经不推荐使用 corpid 和 corpsecret 来调用接口了。我这边暂时已经不用了 ，已经基于目前最新的接口进行了所需的封装，有新的接口需要封装也是快的。

**Comment by atian25** [comment]
@allenm 是钉钉的同学，后续由他们这边跟进。

**Comment by pengdafu** [comment]
烦哦 现在还有人在搞嘛？-_-

**Comment by Akimotorakiyu** [comment]
@pengdafu 开玩笑呢，两年了

**Comment by mani95lisa** [comment]
@allenm 2021年了，还没有计划吗

**Comment by Akimotorakiyu** [comment]
@mani95lisa 凉了这是

**Comment by qq578023708** [comment]
可能应该使用的人不多吧，官方没有精力去多维护一个SDK了，我也使用的 eggjs+egg-sequelize

**Comment by zyf0330** [comment]
https://developers.dingtalk.com/document/app/sdk-download
新版 api 有 sdk 了

**Comment by pengdafu** [comment]
2021年 我都换公司了～ 终于出了

**Comment by atian25** [comment]
因为 云钉一体化 了。。。 钉钉没人做，就阿里云顺便支持下。
